#! /usr/bin/env php
<?php
/**
 * Kerisy Framework
 *
 * PHP Version 7
 *
 * @author          kaihui.wang <hpuwang@gmail.com>
 * @copyright      (c) 2015 putao.com, Inc.
 * @package         kerisy/framework
 * @version         3.0.0
 */
foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (is_file($file)) {
        define('COMPOSER_PATH', dirname($file));
        break;
    }
}
$dir = COMPOSER_PATH."/..";
define("ROOT_PATH", $dir);
require_once COMPOSER_PATH."/autoload.php";
\Kerisy\Foundation\Application::runCmd();